pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews approved
    conditions:
      - '#approved-reviews-by>=2'
      - status-success=Node CI - Check Article Validity & Deploy / check-article (pull_request_target)
      - status-success=Node CI - Check Article Validity & Deploy / deploy-to-preview (pull_request_target)
      - status-success=Danger
      - base=master
    actions:
      merge:
        method: merge
  - name: delete head branch after close
    conditions:
      - closed
    actions:
      delete_head_branch: {}
