name: Deploy Article to Production

on: [push]

***REMOVED***
***REMOVED***
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
    if: github.ref == 'master'
***REMOVED***
***REMOVED***
***REMOVED***
      - uses: actions/checkout@v1
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
